### PR TITLE
Temporary hotfix for new Spotify update

### PR DESCRIPTION
**Pull request by heheleo**
Hello. 

Before anything, just wanted to say thank you for creating and maintaining this plugin. 

I was just wondering about your progress for the fix for the new Spotify version. It seems like it breaks a lot of stuff. I do not know how Spicetify works or functions (I do have a gist on how this plugin functions though), however, it'll be great to tell us your current input to see if people can help or contribute.

My fork has a somewhat working version, however, it's only been tested on my machine. Not sure on how Spotify works to be honest, but here's some of my observations (feel free to criticise):

- they removed `.os-content`
- they added/edited the main window, it looks like the current left padding is too large.
- toggling sidebar does not seem to update the width of the simplebar container, so the width seems to be broken (I had to change some widths)
- im pretty sure that the lyric widths changes for sidebar toggling, however since the width doesn't change now the lyrics stay constant width when sidebar is hidden.

My fork isnt meant for merging - I added a quick hack to include the `spicetify-packages`. Tell me what you think.

Thank you.

(semi working thing)
image

### CODE REVIEW

**Comment by million1156** [comment]
image
just letting you know, works on my machine :) 

thank you for this fix :D 

*ps: the sidebar lyrics is still uncolored, but hey, this is a wip fix! either way amazing job :)* 
image

**Comment by surfbryce** [comment]
@heheleo See this comment I made on the primary bug report: https://github.com/surfbryce/beautiful-lyrics/issues/340#issuecomment-2041230420

It's not that it is a difficult fix, it's just that this happened when I was in the middle of making major changes on my end, so I've already fixed it and have it working but I need to finish the rest of my big changes prior to making an official update. I'm hoping to get something out this month for it.

**Comment by heheleo** [comment]
> @heheleo See this comment I made on the primary bug report: [#340 (comment)](https://github.com/surfbryce/beautiful-lyrics/issues/340#issuecomment-2041230420)
> 
> It's not that it is a difficult fix, it's just that this happened when I was in the middle of making major changes on my end, so I've already fixed it and have it working but I need to finish the rest of my big changes prior to making an official update. I'm hoping to get something out this month for it.
> 
> I'll keep this open for others who come across it and can't wait, once I push out the update I'll close this

Thank you. I have seen the roadmap and cant wait for the new update - seems like it will be game changing.

**Comment by surfbryce** [comment]
@heheleo If you mean the Development project-space, it's not entirely accurate, the cinema/fullscreen views using custom elements (instead of Spotifys) are in fact one of the big changes, but custom lyrics scrolling won't be included.

The other actual change that prevents me from updating right away is that I'm making more changes to how my lyrics service works, which should bring syllable synced lyrics to even more songs (or improve accuracy for those that already have it).

The other one is also permanently improving the repository so that it can be built easily and works for everybody right out of the gate.

So big changes that I'm hoping I can get done soon!

**Comment by SudhanFromGithub** [comment]
> @heheleo See this comment I made on the primary bug report: [#340 (comment)](https://github.com/surfbryce/beautiful-lyrics/issues/340#issuecomment-2041230420)
> 
> It's not that it is a difficult fix, it's just that this happened when I was in the middle of making major changes on my end, so I've already fixed it and have it working but I need to finish the rest of my big changes prior to making an official update. I'm hoping to get something out this month for it.
> 
> I'll keep this open for others who come across it and can't wait, once I push out the update I'll close this

@surfbryce Excited by your announcement of major update coming out end of this month. Thank you! for your work

**Comment by SudhanFromGithub** [comment]
> Hello.
> 
> Before anything, just wanted to say thank you for creating and maintaining this plugin.
> 
> I was just wondering about your progress for the fix for the new Spotify version. It seems like it breaks a lot of stuff. I do not know how Spicetify works or functions (I do have a gist on how this plugin functions though), however, it'll be great to tell us your current input to see if people can help or contribute.
> 
> My fork has a somewhat working version, however, it's only been tested on my machine. Not sure on how Spotify works to be honest, but here's some of my observations (feel free to criticise):
> 
> * they removed `.os-content`
> * they added/edited the main window, it looks like the current left padding is too large.
> * toggling sidebar does not seem to update the width of the simplebar container, so the width seems to be broken (I had to change some widths)
> * im pretty sure that the lyric widths changes for sidebar toggling, however since the width doesn't change now the lyrics stay constant width when sidebar is hidden.
> 
> My fork isnt meant for merging - I added a quick hack to include the `spicetify-packages`. Tell me what you think.
> 
> Thank you.
> 
> (semi working thing) image

Help me to fix this I am using spicetify in Mac. I just want to fix lyrics not showing on full screen issues

**Comment by heheleo** [comment]
For now, try my fork (here)[https://github.com/heheleo/beautiful-lyrics] and install the plugin located in the `build` directory (replace the original). If it does not work, please show me a screenshot. 

Note that this is a hotfix and will probably be never merged into this repo. However, the auto updater means when surfbryce eventually releases the new update, the plugin will eventually update to its master branch again, which is nice.

**Comment by SudhanFromGithub** [comment]
@heheleo I don't know about it please explain what to do? It will help me a lot

**Comment by heheleo** [comment]
> @heheleo I don't know about it please explain what to do? It will help me a lot

Read instructions [here](https://spicetify.app/docs/advanced-usage/extensions/), with [this](https://github.com/heheleo/beautiful-lyrics/raw/main/dist/beautiful-lyrics.js) being the extension file.

**Comment by SudhanFromGithub** [comment]
@heheleo Thanks a lot. I works perfectly 😀

**Comment by aitronssesin** [comment]
@heheleo I think it broke with the latest spicetify version
image

**Comment by heheleo** [comment]
> @heheleo I think it broke image
> 
> *I tested the [previous build](https://github.com/heheleo/beautiful-lyrics/raw/5bca41137e64f293485ceda9b2ba9de6f5e3b9c7/dist/beautiful-lyrics.js) in your repo and for me that worked image

If you don't mind, using the new build, could you try changing songs? 
Thank you.

**Comment by aitronssesin** [comment]
Now it works perfectly! Thank you so much

**Comment by PassiHD2004** [comment]
image
thanks for making my autistic brain finally shut up 👍🏻

**Comment by SudhanFromGithub** [comment]
> image thanks for making my autistic brain finally shut up 👍🏻

What this fullscreen display

**Comment by heheleo** [comment]
@surfbryce Unrelated question but, I see that you've tried Bun out and reverted it. I'm wondering about the reasoning behind that action. Build step issues?

**Comment by surfbryce** [comment]
@heheleo There was an initial move to bun and an attempt to move away from spicetify-creator, however, the built-in Bun build was absolutely terrible and led to my code being 20mb+ compared to the stable 6 it was before.

Really, I should've just used ESBuild and Bun as the environment, but I didn't have that knowledge/experience at the time.

The huge development experience update I've completed (that you'll see in the next update) moves everything to Deno. Bun is VERY new to windows, I'm not comfortable using an environment which may or may not be the best experience for everyone who may want to work on my extension.

Deno I think is the right choice because of how they handle package imports, there's no package.json to store the packages being used, no node_modules folder to gitignore and etc. It makes everything seem very plug-in-play, you just download the extension, install deno, run the test command, and you're running within Spotify without a single hitch or problem.

Deno also has great support for the JSR repository which I am using for everything I publish (part of the improved developer experience, no more having to download my other packages - now called "web-modules" - repository just to run it), overall, Deno is just great!

I also moved away from Spicetify-Creator, entirely custom build process and build structure, the extension isn't even 6mb+ anymore, it's now just 800kb (including both javascript and css, which are two separate files now).

Auto-update has also been completely revamped and improved, javascript and css are downloaded separately (link tag and using esm import). There is also a map file that is separate as well for debugging.

I've already published my tool-chain and the web-modules, you can view the whole bundling and testing code here: https://jsr.io/@socali/spices

Anyways Bun is great and fast and all, but so is Deno, and Deno being ESM first is what really draws my attention to it.

**Comment by heheleo** [comment]
> @heheleo There was an initial move to bun and an attempt to move away from spicetify-creator, however, the built-in Bun build was absolutely terrible and led to my code being 20mb+ compared to the stable 6 it was before.
> 
> Really, I should've just used ESBuild and Bun as the environment, but I didn't have that knowledge/experience at the time.
> 
> The huge development experience update I've completed (that you'll see in the next update) moves everything to Deno. Bun is VERY new to windows, I'm not comfortable using an environment which may or may not be the best experience for everyone who may want to work on my extension.
> 
> Deno I think is the right choice because of how they handle package imports, there's no package.json to store the packages being used, no node_modules folder to gitignore and etc. It makes everything seem very plug-in-play, you just download the extension, install deno, run the test command, and you're running within Spotify without a single hitch or problem.
> 
> Deno also has great support for the JSR repository which I am using for everything I publish (part of the improved developer experience, no more having to download my other "packages" - now called "web-modules" - repository just to run it), overall, Deno is just great!
> 
> I also moved away from Spicetify-Creator, entirely custom build process and build structure, the extension isn't even 6mb+ anymore, it's now just 800kb (including both javascript and css, which are two separate files now).
> 
> Auto-update has also been completely revamped and improved, javascript and css are downloaded separately (link tag and using esm import). There is also a map file that is separate as well for debugging.
> 
> I've already published my tool-chain and the web-modules, you can view the whole bundling and testing code here: [jsr.io/@socali/spices](https://jsr.io/@socali/spices)
> 
> Anyways Bun is great and fast and all, but so is Deno, and Deno being ESM first is what really draws my attention to it.

Great change. I agree with you - Deno is somewhat underrated and is amazing. Your tool chain is awesome - can't wait to see the new extension in action. Although, sometimes I do wonder if this is all overkill for a Spotify extension 😂 however, big props to you. 

And about the progress? It seems like you've still got some code left to write. Seems like your todo list is off sync with the GitHub Project.

**Comment by surfbryce** [comment]
@heheleo To be fair, when I first made this extension and did everything I was doing, a lot of it was considered "overkill", now it's just considered standard!

But honestly, all of this development-experience work isn't just for me, it's in the best interests of the entire Spicetify developer ecosystem. Learning how to setup, then develop, and finally publish a Spicetify extension is a giant pain. Learning how to effectively and efficiently develop an even more complicated extension like my own then becomes an even greater pain.

I have much larger plans as well surrounding this whole developer-concept and ideas on how to grow the ecosystem and interest in it.

Once I finish the release build script (which is just mainly making the release version of the Auto-Update entry-point) I'll make two youtube videos (one for how to setup Beautiful Lyrics so people can contribute, and the other for how to start out with Spicetify using my toolchain/modules) that will release alongside the update. The whole development setup for this project has been a major blocker for a lot of developers who wanted to contribute, and the same goes for making extensions for Spicetify, so I'm hoping I can turn that perception around.

As for the progress, I'm assuming you're looking at the project dashboard or whatever GitHub calls it. I honestly haven't really touched/updated that in a fat year, so yeah, definitely not aligned with how things are going right now.

GitHub makes it a kind of an "out of the way" thing to do, so eventually I want to look into a roadmap visualization solution so that people can view progress easier and I can update it more easily. I'll probably look into that directly after the update and also start work on redoing the README then to.

I appreciate all the interest, thank you, giving me somebody I can tell this all to lol

**Comment by heheleo** [comment]
Closing this due to the new remake coming out today. Please support the author for the new release!

**Comment by heheleo** [comment]
### Reopened this pull request for people looking for a temporary fix, until the release comes out. 

For help installing:
Read instructions [here](https://spicetify.app/docs/advanced-usage/extensions/), with [this](https://github.com/heheleo/beautiful-lyrics/raw/main/dist/beautiful-lyrics.js) being the extension file.
If it doesn't work on startup, try changing songs.

Please wait patiently for the new release! Read more about the progress at #441.

**Comment by heheleo** [comment]
It seems like people are getting double icons from installing this plugin. I unfortunately can't reproduce this issue, but please make sure that there is only **one** beautiful-lyrics file in your Extensions directory (to open the directory, execute `spicetify config-dir` on your PowerShell/terminal).

**Comment by aneesh1122** [comment]
> It seems like people are getting double icons from installing this plugin. I unfortunately can't reproduce this issue, but please make sure that there is only **one** beautiful-lyrics file in your Extensions directory (to open the directory, execute `spicetify config-dir` on your PowerShell/terminal). 

Double icons appear only when you install both your 'beautiful lyrics' and beautiful lyrics from marketplace

**Comment by heheleo** [comment]
> > It seems like people are getting double icons from installing this plugin. I unfortunately can't reproduce this issue, but please make sure that there is only **one** beautiful-lyrics file in your Extensions directory (to open the directory, execute `spicetify config-dir` on your PowerShell/terminal).
> 
> Double icons appear only when you install both your 'beautiful lyrics' and beautiful lyrics from marketplace

If you dont mind, please remove the one from the marketplace and test it out - the fork that I made does not disable the auto update feature, which means eventually when the new release is out, it will update automatically aswell 😄

**Comment by surfbryce** [comment]
@heheleo just saw this, it will not auto-update, the auto-update feature is changing and won't use the same method of auto-updating that it currently does, so it will not auto-update

**Comment by ForkHRVEY** [comment]
How do I install this?

**Comment by surfbryce** [comment]
@heheleo Marketplace uses the metadata.json file, so the index file will be correctly configured so that people do NOT have to reinstall the extension. But the auto-updater itself uses a different method that will not work with the new folder structure the extension will have and the way that the new auto-updater works, naturally, this won't be a problem because people can just reload Spotify and it'll be fine. So they won't have to reinstall the extension (they can if they want), they'll just need to restart Spotify. In most cases, people won't have to do anything manually since they'll probably open Spotify *after* the update so it'll already be running properly anyways

**Comment by Neptune1190** [comment]
image
if this is useful to anyone

**Comment by Neptune1190** [comment]
image
the full imge

**Review by hazukame — APPROVED** [review]

**Comment by heheleo** [comment]
Closing this pull request. The new release is coming out... in a few minutes!

**Pull request closed without merging**
