### PR TITLE
Merge 4.0.0 Stable-Build into Main

### PR DESCRIPTION
**Pull request by surfbryce**
LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

### CODE REVIEW

**Comment by sanoojes** [comment]
yeahh

**Comment by Cristioro** [comment]
GOOD!!!!!!

Thanks Surfbryce

**Comment by IcyColdified** [comment]
Very nice!

I gotta ask though, why is my Spotify accessToken getting sent to your backend??

**Comment by surfbryce** [comment]
@IcyColdified My Lyrics Service uses the Spotify AccessToken to make requests to the Spotify API (this is actually the only thing the accessToken can do, so there is no security concern in any regard).

The reasoning for having to do these requests on the Service side rather than extension side is so that my Service has better context of what Song releases we should be looking to gather Lyrics from (and weighing our options), obviously I can't just be accepting any information from the Client so this is the proper way of going about it.

I announced that I would be doing this in one of the releases a while back (one of the latest ones, don't remember which and don't have the time to check); obviously it's been quite a while since that, but I did publicly announce my plans and as to why a long time ago so that people would be prepared for this change (just in case they weren't aware of the Security implications of using the accessToken or were curious)

**Comment by IcyColdified** [comment]
> @IcyColdified My Lyrics Service uses the Spotify AccessToken to make requests to the Spotify API (this is actually the only thing the accessToken can do, so there is no security concern in any regard).
> 
> The reasoning for having to do these requests on the Service side rather than extension side is so that my Service has better context of what Song releases we should be looking to gather Lyrics from (and weighing our options), obviously I can't just be accepting any information from the Client so this is the proper way of going about it.
> 
> I announced that I would be doing this in one of the releases a while back (one of the latest ones, don't remember which and don't have the time to check); obviously it's been quite a while since that, but I did publicly announce my plans and as to why a long time ago so that people would be prepared for this change (just in case they weren't aware of the Security implications of using the accessToken or were curious)

Ah, now I understand. Thank you!

**Pull request merged**
